services:
  mysql:
    image: mysql:8.0
    container_name: labeltool-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=labeltool_root_2025
      - MYSQL_DATABASE=labeltool_db
      - MYSQL_USER=labeltool_user
      - MYSQL_PASSWORD=labeltool_pass_2025
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/scripts/mysql_init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - labeltool-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "labeltool_user", "-plabeltool_pass_2025"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: labeltool-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_RELOAD=false
      - LOG_LEVEL=INFO
      - UPLOAD_DIR=/app/uploads
      - REMOVAL_DIR=/app/removal
      - GENERATED_DIR=/app/generated
      - MAX_FILE_SIZE=52428800  # 50MB
      - PADDLEOCR_DEVICE=cpu
      - PADDLEOCR_LANG=japan
      - IOPAINT_PORT=8081
      - CORS_ORIGINS="http://localhost:3000,http://localhost:5173,http://frontend"
      - DATABASE_URL=mysql+aiomysql://labeltool_user:labeltool_pass_2025@mysql:3306/labeltool_db?charset=utf8mb4
      - DATABASE_ECHO=false
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=labeltool_user
      - MYSQL_PASSWORD=labeltool_pass_2025
      - MYSQL_DATABASE=labeltool_db
    volumes:
      - backend_data:/app/data  # Persistent data directory (database)
      - backend_uploads:/app/uploads
      - backend_removal:/app/removal
      - backend_generated:/app/generated
      - backend_exports:/app/exports
      - backend_logs:/app/logs
      - paddlex_cache:/root/.paddlex
    depends_on:
      mysql:
        condition: service_healthy
      iopaint-service:
        condition: service_healthy
    networks:
      - labeltool-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/', timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: labeltool-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - labeltool-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  iopaint-service:
    build:
      context: ./iopaint-service
      dockerfile: Dockerfile
    container_name: labeltool-iopaint
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - IOPAINT_HOST=0.0.0.0
      - IOPAINT_PORT=8081
      - IOPAINT_MODEL=lama
      - IOPAINT_DEVICE=cpu
      - IOPAINT_LOW_MEM=true
      - IOPAINT_CPU_OFFLOAD=true
      - IOPAINT_NO_GUI=true
      - LOG_LEVEL=INFO
    volumes:
      - huggingface_cache:/root/.cache/huggingface
      - iopaint_temp:/app/temp
    networks:
      - labeltool-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  mysql_data:
    driver: local
  backend_data:
    driver: local
  backend_uploads:
    driver: local
  backend_removal:
    driver: local
  backend_generated:
    driver: local
  backend_exports:
    driver: local
  backend_logs:
    driver: local
  huggingface_cache:
    driver: local
  paddlex_cache:
    driver: local
  iopaint_temp:
    driver: local

networks:
  labeltool-network:
    driver: bridge