services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: labeltool-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_RELOAD=false
      - LOG_LEVEL=INFO
      - UPLOAD_DIR=/app/uploads
      - PROCESSED_DIR=/app/processed
      - MAX_FILE_SIZE=52428800  # 50MB
      - PADDLEOCR_DEVICE=cpu
      - IOPAINT_PORT=8081
      - CORS_ORIGINS="http://localhost:3000,http://localhost:5173,http://frontend"
    volumes:
      - backend_uploads:/app/uploads
      - backend_processed:/app/processed
      - backend_exports:/app/exports
      - backend_logs:/app/logs
      - paddlex_cache:/root/.paddlex
    depends_on:
      iopaint-service:
        condition: service_healthy
    networks:
      - labeltool-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/', timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: labeltool-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - labeltool-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  iopaint-service:
    build:
      context: ./iopaint-service
      dockerfile: Dockerfile
    container_name: labeltool-iopaint
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - IOPAINT_HOST=0.0.0.0
      - IOPAINT_PORT=8081
      - IOPAINT_MODEL=lama
      - IOPAINT_DEVICE=cpu
      - IOPAINT_LOW_MEM=true
      - IOPAINT_CPU_OFFLOAD=true
      - IOPAINT_NO_GUI=true
      - LOG_LEVEL=INFO
    volumes:
      - huggingface_cache:/root/.cache/huggingface
      - iopaint_temp:/app/temp
    networks:
      - labeltool-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  backend_uploads:
    driver: local
  backend_processed:
    driver: local
  backend_exports:
    driver: local
  backend_logs:
    driver: local
  huggingface_cache:
    driver: local
  paddlex_cache:
    driver: local
  iopaint_temp:
    driver: local

networks:
  labeltool-network:
    driver: bridge